### ISSUE TITLE
Docset generation broken

### ISSUE THREAD

**Issue by anoopknayak** [giladgray/dash-bluebird-docset#1]
When i run

``` bash
coffee docset.coffee
```

I get the following error: 

```
Error: ENOENT, no such file or directory 'bluebird.docset/Contents/Resources/Documents/github-markdown.css'
  at Error (native)
  at Object.fs.openSync (fs.js:502:18)
  at Object.fs.writeFileSync (fs.js:1103:15)
  at Object.<anonymous> (/Users/Anoop/Documents/Development/dash-bluebird-docset/docset.coffee:28:4)
  at Object.<anonymous> (/Users/Anoop/Documents/Development/dash-bluebird-docset/docset.coffee:1:1)
  at Module._compile (module.js:460:26)
```

Have you missed some files?

**Comment by giladgray** [comment]
`npm install` my friend :)

NPM brings in github-markdown-css and the script copies it to the docset.

What are you trying to accomplish? The docset can be installed from Dash's
User Contributed Docsets section, although bluebird has probably updated a
bit since I last generated it.

**Comment by anoopknayak** [comment]
I did that before. And it installed the modules successfully. I retried it again after removing node-modules and re-running `npm install`. Still the same output from the `coffee docset.coffee`

I just want to get the latest bluebird api(as again its been changed since february, not significantly though'. And also when i use the existing bluebird.docset, it is showing `File not found` in dash.
Btw thanks for the quick response :)

**Comment by giladgray** [comment]
Hey sorry to leave you hanging for a week, I was on vacation last week but I'm taking a look at this now. I'm not seeing the missing file error here so I'm happy to generate a new version of the docset for the latest version (2.9.27).

**Comment by giladgray** [comment]
@anoopknayak see Kapeli/Dash-User-Contributions#483

**Comment by giladgray** [comment]
And I figured out the issue here: there's no `Documents` directory in `bluebird.docset/Contents/Resources/`. It exists on my box but not in the repo.

**Comment by anoopknayak** [comment]
thanks :)
